server:
  address: 127.0.0.1
  port: 8090

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/learn
      username: root
      password: lvshuo1234

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

