server:
  address: 127.0.0.1
  port: 9091

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/learn
      username: learn
      password: MFR77Jh7BPGTaD3G

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

